"""Initial migration

Revision ID: b894b12903a4
Revises: 
Create Date: 2025-02-10 16:36:33.868641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b894b12903a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog") as batch_op:
        batch_op.alter_column("user_id", new_column_name="author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog") as batch_op:
        batch_op.alter_column("author_id", new_column_name="user_id")
